// Generated by gencpp from file req_b_pkg/HeaderAndReading.msg
// DO NOT EDIT!


#ifndef REQ_B_PKG_MESSAGE_HEADERANDREADING_H
#define REQ_B_PKG_MESSAGE_HEADERANDREADING_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace req_b_pkg
{
template <class ContainerAllocator>
struct HeaderAndReading_
{
  typedef HeaderAndReading_<ContainerAllocator> Type;

  HeaderAndReading_()
    : header()
    , sensors_data()
    , x(0.0)
    , y(0.0)
    , th(0.0)  {
    }
  HeaderAndReading_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensors_data(_alloc)
    , x(0.0)
    , y(0.0)
    , th(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _sensors_data_type;
  _sensors_data_type sensors_data;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _th_type;
  _th_type th;





  typedef boost::shared_ptr< ::req_b_pkg::HeaderAndReading_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::req_b_pkg::HeaderAndReading_<ContainerAllocator> const> ConstPtr;

}; // struct HeaderAndReading_

typedef ::req_b_pkg::HeaderAndReading_<std::allocator<void> > HeaderAndReading;

typedef boost::shared_ptr< ::req_b_pkg::HeaderAndReading > HeaderAndReadingPtr;
typedef boost::shared_ptr< ::req_b_pkg::HeaderAndReading const> HeaderAndReadingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::req_b_pkg::HeaderAndReading_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::req_b_pkg::HeaderAndReading_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::req_b_pkg::HeaderAndReading_<ContainerAllocator1> & lhs, const ::req_b_pkg::HeaderAndReading_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.sensors_data == rhs.sensors_data &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.th == rhs.th;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::req_b_pkg::HeaderAndReading_<ContainerAllocator1> & lhs, const ::req_b_pkg::HeaderAndReading_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace req_b_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::req_b_pkg::HeaderAndReading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::req_b_pkg::HeaderAndReading_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::req_b_pkg::HeaderAndReading_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::req_b_pkg::HeaderAndReading_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::req_b_pkg::HeaderAndReading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::req_b_pkg::HeaderAndReading_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::req_b_pkg::HeaderAndReading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6826ae3bb61eb4a4d97f1f78b84604c";
  }

  static const char* value(const ::req_b_pkg::HeaderAndReading_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6826ae3bb61eb4aULL;
  static const uint64_t static_value2 = 0x4d97f1f78b84604cULL;
};

template<class ContainerAllocator>
struct DataType< ::req_b_pkg::HeaderAndReading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "req_b_pkg/HeaderAndReading";
  }

  static const char* value(const ::req_b_pkg::HeaderAndReading_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::req_b_pkg::HeaderAndReading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[] sensors_data\n"
"float64 x\n"
"float64 y\n"
"float64 th \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::req_b_pkg::HeaderAndReading_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::req_b_pkg::HeaderAndReading_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensors_data);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.th);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HeaderAndReading_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::req_b_pkg::HeaderAndReading_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::req_b_pkg::HeaderAndReading_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sensors_data[]" << std::endl;
    for (size_t i = 0; i < v.sensors_data.size(); ++i)
    {
      s << indent << "  sensors_data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sensors_data[i]);
    }
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "th: ";
    Printer<double>::stream(s, indent + "  ", v.th);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REQ_B_PKG_MESSAGE_HEADERANDREADING_H
