// Generated by gencpp from file req_c_pkg/HeaderAndReadings.msg
// DO NOT EDIT!


#ifndef REQ_C_PKG_MESSAGE_HEADERANDREADINGS_H
#define REQ_C_PKG_MESSAGE_HEADERANDREADINGS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>

namespace req_c_pkg
{
template <class ContainerAllocator>
struct HeaderAndReadings_
{
  typedef HeaderAndReadings_<ContainerAllocator> Type;

  HeaderAndReadings_()
    : header()
    , angles()
    , sensors_data()
    , poses()  {
    }
  HeaderAndReadings_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , angles(_alloc)
    , sensors_data(_alloc)
    , poses(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _angles_type;
  _angles_type angles;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _sensors_data_type;
  _sensors_data_type sensors_data;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _poses_type;
  _poses_type poses;





  typedef boost::shared_ptr< ::req_c_pkg::HeaderAndReadings_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::req_c_pkg::HeaderAndReadings_<ContainerAllocator> const> ConstPtr;

}; // struct HeaderAndReadings_

typedef ::req_c_pkg::HeaderAndReadings_<std::allocator<void> > HeaderAndReadings;

typedef boost::shared_ptr< ::req_c_pkg::HeaderAndReadings > HeaderAndReadingsPtr;
typedef boost::shared_ptr< ::req_c_pkg::HeaderAndReadings const> HeaderAndReadingsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::req_c_pkg::HeaderAndReadings_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::req_c_pkg::HeaderAndReadings_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::req_c_pkg::HeaderAndReadings_<ContainerAllocator1> & lhs, const ::req_c_pkg::HeaderAndReadings_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.angles == rhs.angles &&
    lhs.sensors_data == rhs.sensors_data &&
    lhs.poses == rhs.poses;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::req_c_pkg::HeaderAndReadings_<ContainerAllocator1> & lhs, const ::req_c_pkg::HeaderAndReadings_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace req_c_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::req_c_pkg::HeaderAndReadings_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::req_c_pkg::HeaderAndReadings_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::req_c_pkg::HeaderAndReadings_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::req_c_pkg::HeaderAndReadings_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::req_c_pkg::HeaderAndReadings_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::req_c_pkg::HeaderAndReadings_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::req_c_pkg::HeaderAndReadings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b282dd3d5a07588f4f04a69f41539577";
  }

  static const char* value(const ::req_c_pkg::HeaderAndReadings_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb282dd3d5a07588fULL;
  static const uint64_t static_value2 = 0x4f04a69f41539577ULL;
};

template<class ContainerAllocator>
struct DataType< ::req_c_pkg::HeaderAndReadings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "req_c_pkg/HeaderAndReadings";
  }

  static const char* value(const ::req_c_pkg::HeaderAndReadings_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::req_c_pkg::HeaderAndReadings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[] angles\n"
"float64[] sensors_data\n"
"\n"
"geometry_msgs/Vector3[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::req_c_pkg::HeaderAndReadings_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::req_c_pkg::HeaderAndReadings_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.angles);
      stream.next(m.sensors_data);
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HeaderAndReadings_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::req_c_pkg::HeaderAndReadings_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::req_c_pkg::HeaderAndReadings_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "angles[]" << std::endl;
    for (size_t i = 0; i < v.angles.size(); ++i)
    {
      s << indent << "  angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angles[i]);
    }
    s << indent << "sensors_data[]" << std::endl;
    for (size_t i = 0; i < v.sensors_data.size(); ++i)
    {
      s << indent << "  sensors_data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sensors_data[i]);
    }
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // REQ_C_PKG_MESSAGE_HEADERANDREADINGS_H
